database:
  host: localhost
  password: secret
  port: 5432
  user: admin
logging:
  file:
    backup_count: 3
    max_size: 10MB
    path: /var/log/app.log
    store_all: false
  handlers:
  - console
  - file
  level: INFO
server:
  host: 0.0.0.0
  port: 8080
